### ISSUE TITLE
[Enhancement]: Add "How to play?" section

### ISSUE THREAD

**Issue by Harsh-Burman** [ChromeGaming/Squard-line#101]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement:

As part of improving the user experience and guiding players through the game, we propose adding a "How to Play" section to the game interface. This section will provide clear instructions and guidance on how to play the game effectively, helping new players understand the gameplay mechanics and objectives.

### Describe the solution you'd like

I will add a section card beside the introduction card describing game instructions
![gameplay](https://github.com/ChromeGaming/Squard-line/assets/138804467/bb87e7f8-1706-427f-b1da-8f06e66448f6)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by dvnshi** [comment]
Please assign this issue to me under GSSOC .

**Comment by Durgesh4993** [comment]
https://github.com/ChromeGaming/Squard-line/assets/98798977/04f519ba-e5ed-4868-8204-f609b5083fe8

**Comment by Durgesh4993** [comment]
@Harsh-Burman Why did't you try this type

**Comment by NandRabadiya** [comment]
@Durgesh4993  sir, I can work on the issue mentioned above .
Assign it to me !!

**Comment by zerotwoadarsh** [comment]
I would like to work on this issue. Can you assign it to me?
