### ISSUE TITLE
[Bug]: Footer inaccessible if 'Lets play' or 'Restart' not clicked

### ISSUE THREAD

**Issue by ayush-848** [ChromeGaming/Squard-line#109]
### Give a brief about the bug ✍️

Footer inaccessible if 'Lets play' or 'Restart' not clicked

![image](https://github.com/ChromeGaming/Squard-line/assets/126975547/261f4484-9824-414a-86db-e2e7962a8488)

### What is the expected behavior? 🤔

The social media link should me accessed 

### Provide step by step information reproduce the bug 📄

1. Go to the page
2. Scroll down

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-848** [comment]
@Durgesh4993 Please assign this issue to me.

**Comment by Mukesh751** [comment]
go ahead
