### ISSUE TITLE
[New Feature]: preloader

### ISSUE THREAD

**Issue by gangwarsomya** [ChromeGaming/Squard-line#117]
### 🎮 feature Request

A animation should render while the page is being loaded

### Point down the features

A animation should render while the page is being loaded

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!

**Comment by Mukesh751** [comment]
go ahead

**Comment by shashbh18** [comment]
I would love to work on it.Please assign this issue to me.
