### ISSUE TITLE
icon hover 

### ISSUE THREAD

**Issue by aashkaaaaaa** [ChromeGaming/Squard-line#119]
### 🎮 feature Request

![image](https://github.com/ChromeGaming/Squard-line/assets/138461600/4125e6e1-244a-4f9b-a0ca-b5f3ebda57b9)

### Point down the features

a hover for icon

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Gokilp** [comment]
please the assign the issue to i work on issue

**Comment by Mukesh751** [comment]
similar issue is already raised #106
