### ISSUE TITLE
[Bug]:  Overlapping issue

### ISSUE THREAD

**Issue by shruti110503** [ChromeGaming/Squard-line#120]
### Give a brief about the bug ✍️

There is overlapping issue as shown in the ss below-
![Screenshot 2024-06-06 010514](https://github.com/ChromeGaming/Squard-line/assets/118251562/fa785c92-f8c0-4d9f-b208-722942b8d107)

### What is the expected behavior? 🤔

Everything should be separate and readable.

### Provide step by step information reproduce the bug 📄

Please assign me this under gssoc'24.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by shagungarg645** [comment]
Please assign me this issue to work upon.

**Comment by Mukesh751** [comment]
its already fixed please mention some other improvements so that i can assign it to you
