### ISSUE TITLE
[Bug]:  Need improvement  Contribution.md file 

### ISSUE THREAD

**Issue by Gokilp** [ChromeGaming/Squard-line#121]
### Give a brief about the bug ✍️

Description

Need a improvement Readme file  and Contribution.md file 

Description

i will  improve Contributors.md file  and Contribution.md

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Mukesh751** [comment]
How are you going to improve it?

**Comment by Gokilp** [comment]
optimize  the readable format

**Comment by Mukesh751** [comment]
how are you going to optimize ?

**Comment by Gokilp** [comment]
understood readable Format

**Comment by Mukesh751** [comment]
not required
