### ISSUE TITLE
[Bug]: Typo in Website Title

### ISSUE THREAD

**Issue by Samridhi002** [ChromeGaming/Squard-line#122]
### Give a brief about the bug ✍️

# Description

There is a typo in the website title. The current title is "Squared Line," but it should be "**_Squard-line._**"

# Attachment:
![Screenshot (40)](https://github.com/ChromeGaming/Squard-line/assets/169380578/513a4424-5f6e-488f-bac2-7c30de27ddad)

@Mukesh751 
Please assign me this issue. Thank you!

### What is the expected behavior? 🤔

The browser tab title should be "**_Squard-line._**"

### Provide step by step information reproduce the bug 📄

1. Navigate to the website's homepage (URL of the website).
2. Look at the title displayed on the browser tab.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by kashi-verma** [comment]
I will quick fix this issue so i request to @Durgesh4993  to kindly assign me this issue.
Thank you

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**

**Comment by Garvanand** [comment]
> **hello, please assign this issue to me under GSSOC'24.**

Already rectified it buddy and raised the PR for the same

**Comment by Garvanand** [comment]
@Durgesh4993  Kindly review the PR and close the issue
