### ISSUE TITLE
[New Feature]: Dockerize the app

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [ChromeGaming/Squard-line#128]
### 🎮 feature Request

I want to tell you that we have to dockerize the app because when in future anyone want to clone our app and use our app in different operating system then our project dont run in their system so for removing this problem we have to dockerize the app so that everyone can easily use our app

### Point down the features

when someone clone or run app in different operating system then he simply use
when someone use different version of package in own system then it create virtual environment and use this app
in future when this version in corrupted then someone want to use this app then user can use
after dockerize the app you can also publish image on dockerhub

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Mukesh751** [comment]
Since its only made of HTML CSS and JS (as their version usually not changed) so I don't think we need to dockerize it. Please, let me know if you have any queries.

**Comment by agarwalhimanshugaya** [comment]
sir html css and js can be dockerize using nginx which load balance your website and also after containerize the app you can simple deploy your app using kubernetes and other cloud platform

**Comment by agarwalhimanshugaya** [comment]
i can dockerize your app also i can kubernetes your app

**Comment by agarwalhimanshugaya** [comment]
@Mukesh751 sr plz review my pr i write docker file and kubernetes file both
