### ISSUE TITLE
[Bug]: mail icon not proper

### ISSUE THREAD

**Issue by AMS003010** [ChromeGaming/Squard-line#131]
### Give a brief about the bug ✍️

The expected the mail icon seems to be wrong. It can be replaced with an appropriate one

### What is the expected behavior? 🤔

An appropriate mail icon would greatly enhance the usability of the application

### Provide step by step information reproduce the bug 📄

1. Go the [website](https://chromegaming.github.io/Squard-line/)
2. Scroll down
3. Find the bug in the footer section

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**

**Comment by Mukesh751** [comment]
@AMS003010 go ahead

**Comment by AMS003010** [comment]
Hello @Mukesh751 🤗

I have made the PR. Please do review it.
