### ISSUE TITLE
[New Feature]: create a custom 404 not found page for the website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [ChromeGaming/Squard-line#132]
### 🎮 feature Request

create a custom 404 not found page for the website

### Point down the features

![image](https://github.com/ChromeGaming/Squard-line/assets/125277258/a2dee5bc-32da-4b66-9312-77b6be2b3fb7)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Mukesh751** [comment]
@RamakrushnaBiswal go ahead
