### ISSUE TITLE
Improvement needed in footer section.

### ISSUE THREAD

**Issue by Braj-01** [ChromeGaming/Squard-line#133]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Catching footer section is not there .
I would like to @admin pls assign me this task so that I can improve it.

### Describe the solution you'd like

Solution steps

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**

**Comment by Sadhvika1** [comment]
please assign this issue to me under GSSOC'24.

**Comment by Mukesh751** [comment]
@Braj-01 how are you gonna improve it?

**Comment by Braj-01** [comment]
@Mukesh751 The mail image is not displaying when opening the site so I m gonna fixing that.

**Comment by Mukesh751** [comment]
@Braj-01 check #131 someone is already assigned that task.
