### ISSUE TITLE
Documentation Fix

### ISSUE THREAD

**Issue by nimitagarwal26** [ChromeGaming/Squard-line#136]
### Describe the bug ✍️

The documentation does not contain the technology used section. A good documentation must contain what all techs are being used in the project.
I would love to fix this documentation issue. Please assign it to me under GSSoC'24 and please add level to it.

### Provide step by step information reproduce the bug 📄

I will add all the tech stacks used in the project.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Mukesh751** [comment]
its already mentioned in side part...so i don't think we need this.
