### ISSUE TITLE
[Documentation Bug]: Add contributing.md file

### ISSUE THREAD

**Issue by Priyanshu2631** [ChromeGaming/Squard-line#141]
### Describe the bug ✍️

There is no contributing.md file in this repository which gives instructions and helps beginners to contribute with ease.

### Provide step by step information reproduce the bug 📄

I wanna add the contributing.md file which will give instruction how to contribute, also using GitHub Desktop and links on forking,etc.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Mukesh751** [comment]
its already there i guess

**Comment by Priyanshu2631** [comment]
> its already there i guess

Srry it's there,can I update it with GitHub Desktop instructions and other improvements.

**Comment by Mukesh751** [comment]
> > its already there i guess
> 
> Srry it's there,can I update it with GitHub Desktop instructions and other improvements.

go ahead
