### ISSUE TITLE
[Documentation Bug]: Missing Project Description and Potential README Improvements

### ISSUE THREAD

**Issue by Nidhi1314** [ChromeGaming/Squard-line#144]
### Missing Project Description:
The current README file lacks a clear description of what Squard-line is and what it does.
Including a concise yet informative description would be beneficial for potential contributors and users who want to understand the project at a glance.

### Potential Improvements:
* **Contribution Guidelines:** In the "How to make a PR in a Project" section, a sentence at the beginning could clarify what kind of contributions are welcome (e.g. bug fixes, new features, documentation improvements).
* **Badges:** The generic badges like "Built with love" could be replaced with more specific ones reflecting the technologies used (e.g. programming languages, frameworks).

### Proposed Action:

* I can draft a clear and concise project description based on the available information and update the contribution guidelines and badges section as stated above.

Please let me know if you'd like me to proceed with changes in Readme

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Mukesh751** [comment]
@Nidhi1314 go ahead
