### ISSUE TITLE
[Documentation Bug]: techstack misssinh

### ISSUE THREAD

**Issue by Debayan-Ghosh2005** [ChromeGaming/Squard-line#150]
### Describe the bug ✍️

there is no option use techstack in this project

### Provide step by step information reproduce the bug 📄

i will add the techstack logo of the project .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Mukesh751** [comment]
language section show the same thing i guess
