### ISSUE TITLE
[New Feature]:  adding instagram, x and facebook in social media section

### ISSUE THREAD

**Issue by dnyandeepchute** [ChromeGaming/Squard-line#152]
### 🎮 feature Request

adding instagram, x and facebook in social media section

### Point down the features

adding instagram, x and facebook in social media section

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by dnyandeepchute** [comment]
please assign this to me, thank you.

**Comment by IshaanXCoder** [comment]
Heyy, pls assign this to me! thank you!

**Comment by Mukesh751** [comment]
it was already there but somehow i got removed please fix this
