### ISSUE TITLE
Text is not visible in the footer section due to color of font

### ISSUE THREAD

**Issue by ahinagangopadhyay** [ChromeGaming/Squard-line#157]
The footer section text is not visible as it almost seems to overlap with the footer background.
The color can be changed to something more readable.

![Screenshot (124)](https://github.com/ChromeGaming/Squard-line/assets/159465464/ca285606-c9ed-475d-94d0-91952fd2e413)
Please assign this issue to me under GSSOC'24

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Karthikkariappa08** [comment]
plz assign this task to me

**Comment by Mukesh751** [comment]
@ahinagangopadhyay go ahead

**Comment by ahinagangopadhyay** [comment]
@Mukesh751 I have opened a pull request to solve this issue.Please review the request.
