### ISSUE TITLE
[New Feature]: Adding Gmail, Linkedin icons in the footer for convenient connections

### ISSUE THREAD

**Issue by Rajul-29** [ChromeGaming/Squard-line#159]
### 🎮 feature Request

Gmail and Linkedin icons (with your links) addition in the footer after connect with me, which will make it easier for the website visitors to connect with the website owner

### Point down the features

Website visitors can just click on those small icons to open your Linkedin account or directly email the website owner

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Rajul-29** [comment]
I hope this message finds you well. I am a contributor selected for GirlScript Summer of Code and I would like to work on this issue in your repository. Could you please assign it to me?

Thank you!

Best regards,
Rajul Chaudhary

**Comment by Soujanya2004** [comment]
Hi, I have been following your project and I would love to contribute, can you please assign me this issue.

**Comment by Mukesh751** [comment]
someone is already working on the same issue
