### ISSUE TITLE
Alter How to play 

### ISSUE THREAD

**Issue by 21pa1a6149** [ChromeGaming/Squard-line#161]
### Give a brief about the bug ✍️

The content in How to play i.e in gameplay,scoring,winning is not clearly visible due to its font colors.

### What is the expected behavior? 🤔

I will change How to play section content color so it will look clearly visible to the players while reading How to play before they start the game.
![Screenshot 2024-06-23 121802](https://github.com/ChromeGaming/Squard-line/assets/126564098/9d123778-d4f6-41a3-a412-432087b36640)

### Provide step by step information reproduce the bug 📄

Description

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Soujanya2004** [comment]
Hi, I have been following your project and I would love to contribute, can you please assign me this issue.

**Comment by minakshikr7** [comment]
Please assign me this issue under @GSS0C24

**Comment by Mukesh751** [comment]
someone is already working on the same issue
