### ISSUE TITLE
Change color and font 

### ISSUE THREAD

**Issue by supriyagaut** [ChromeGaming/Squard-line#163]
![Screenshot 2024-06-23 141203](https://github.com/ChromeGaming/Squard-line/assets/141560711/5828a289-2c5d-4139-b0e3-177e3a92edc0)
@ChromeGaming  Adding a proper font size and color enhances the look of the website.
kindly assign me this issue under  GSSOC'24.

**Comment by Soujanya2004** [comment]
hi @supriyagaut can u assign me for this task i can surely enhance the font and color of the text by adding proper styling

**Comment by minakshikr7** [comment]
Please assign me this issue under @GSS0C24

**Comment by Mukesh751** [comment]
someone is already working on the same
