### ISSUE TITLE
[Bug]: Footer text is Repeated

### ISSUE THREAD

**Issue by Saipradyumnagoud** [ChromeGaming/Squard-line#167]
### Give a brief about the bug ✍️

Description
In the website the footer text is repated 
due to that the user gets confuesd

### What is the expected behavior? 🤔

Description
i will remove the duplicate footer

### Provide step by step information reproduce the bug 📄

Description
Removing the duplicate footer

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Saipradyumnagoud** [comment]
@Durgesh4993 Please assign me the issue

**Comment by Soujanya2004** [comment]
Hi, I have been following your project and I would love to contribute, can you please assign me this issue.

**Comment by Mukesh751** [comment]
@Saipradyumnagoud go ahead
