### ISSUE TITLE
[New Feature]: Adding custom gameoever alert instead of default browser ones

### ISSUE THREAD

**Issue by YooAshu** [ChromeGaming/Squard-line#17]
### 🎮 feature Request

Adding custom gameoever alert instead of default browser ones 

![Screenshot 2024-05-10 211808](https://github.com/GameSphere-MultiPlayer/Squard-line/assets/95643200/78d6ebd7-ff04-477d-be64-37180ddf2b70)

### Point down the features

the alert will have animation and sound 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by pandey079** [comment]
Please assign it to me

**Comment by IshaSaini11** [comment]
Hey, I can work for this issue, please assign the issue. Also, can you please add the GSSoC and level tag to the issue.

**Comment by Durgesh4993** [comment]
@IshaSaini11 @pandey079  Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by bhairabmahato** [comment]
Hey, I want to work for this issue, please assign the issue.
