### ISSUE TITLE
[Bug]:  Added same data multiple times in footer

### ISSUE THREAD

**Issue by GAVINESHWAR** [ChromeGaming/Squard-line#174]
### Give a brief about the bug ✍️

In the footer section There is added the same content again , I would like to remove the duplicate data and make proper effects to those data.

### What is the expected behavior? 🤔

Removing  that data make the footer section redundancy free.

### Provide step by step information reproduce the bug 📄

Removing this duplicate section
![image](https://github.com/ChromeGaming/Squard-line/assets/124431955/f2b20512-249c-4e88-bc78-0b902583e91e)

@Durgesh4993  , assign me this issue to make contribution to the project.

Thank you

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Mukesh751** [comment]
someone is already working on the same
