### ISSUE TITLE
[Bug]: Background Text Visibility Issue on ChromeGaming!

### ISSUE THREAD

**Issue by SCR01** [ChromeGaming/Squard-line#179]
### Give a brief about the bug ✍️

The background text on the ChromeGaming site is not visible, which creates readability issues and makes it difficult to interact with the site.

The text blends into the background, making it hard to read and navigate the site properly.

![Screenshot 2024-07-20 125054](https://github.com/user-attachments/assets/eaa3c1f9-c9dc-447d-b87c-89bd8072b0a6)

### What is the expected behavior? 🤔

The background text should be clearly visible against the site background to ensure good readability. 

### Provide step by step information reproduce the bug 📄

- Inspect the Element: Right-click on the problematic text and select "Inspect" to find the CSS class or ID.

- Edit the CSS: Locate the CSS file and change the text color to ensure better contrast.

- Test Locally: Save the changes and refresh the browser to verify the fix.

- Commit and Deploy: Commit the changes to your version control and deploy to the production server.

- Verify the Fix: Check the live site to ensure the issue is resolved and the text is readable.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Mukesh751** [comment]
someone is already working on the same
