### ISSUE TITLE
[New Feature]: Adding Sound effects

### ISSUE THREAD

**Issue by YooAshu** [ChromeGaming/Squard-line#18]
### 🎮 feature Request

adding sound effet is necessary for this game, as withound sound the game does not look that enjoyable

### Point down the features

while selecting the boxes a small sound will be played

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this!!

**Comment by Nih1tGupta** [comment]
I would like to work on this issue. Pls assign me this!!

**Comment by Durgesh4993** [comment]
@Nih1tGupta @Rish-tech1 Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
