### ISSUE TITLE
[New Feature]: Add undo and restart functions 

### ISSUE THREAD

**Issue by P-lavanya16** [ChromeGaming/Squard-line#51]
### 🎮 feature Request

If a player wants to reverse their position in a game to improve their score, they may need to  undo there position of the game

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Tarungupta18** [comment]
assign me

**Comment by Durgesh4993** [comment]
@Tarungupta18 Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
