### ISSUE TITLE
UI Enhancement: 

### ISSUE THREAD

**Issue by nidhaahmed** [ChromeGaming/Squard-line#6]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The user interface (UI) of the project could benefit from improvements, particularly regarding visibility and clarity. The logo or words mentioned at the right bottom corner are not easily visible, which impacts user experience negatively.

### Describe the solution you'd like

Solution steps
1. Enhance visibility and clarity of elements in the UI, especially the logo or text at the right bottom corner.
2. Improve overall aesthetics and usability of the UI to provide a better user experience.

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by nidhaahmed** [comment]
Hello,

I'd like to provide some additional context regarding the UI enhancement issue. Currently, the visibility of the logo or text placed at the right bottom corner of the interface is suboptimal, which can be a usability concern, particularly for users accessing the project on smaller screens or devices with lower resolutions.

Improving the visibility of these elements will not only enhance the aesthetic appeal of the UI but also contribute to a more user-friendly experience for all users. By making the logo or text easily visible, we can ensure that important information is readily accessible and doesn't go unnoticed by users.

I'm looking forward to collaborating on this issue and implementing solutions that enhance the overall UI design and usability of the project.

Best regards,
Nidha Ahmed Mohammad.

**Comment by Divyanshi1002** [comment]
Hello,

With my skills in HTML, CSS, and JavaScript, I am well-equipped to tackle this challenge and make a meaningful impact on the project. 
Enhancing the visibility of the logo or text in the bottom right corner of the interface is crucial for improving usability, especially on smaller screens or devices with lower resolutions. 
Let's work together to implement solutions that not only enhance the aesthetic appeal of the UI but also contribute to a more user-friendly experience for all users.

Regards,
Divyanshi Kanwar 
GSSOC'24 contributor

**Comment by ridhi-ahuja** [comment]
Hello , as a Contributor in GS'SOC 2024 I am looking forward on working and contributing in this project and implement some changes .
I've developed skills in JAVA , C , Javascript ,Python , WEB development and basic Machine Learning ,currently under Artificial Intelligence training on implementing AI tools ,exploring more in tech.

**Comment by Ramu-chiluveru** [comment]
As a GSsoc'24 contributer. I'd like to provide some additional context regarding the UI enhancement issue.So, i request you to assign this to me @

**Comment by Aanya10Mishra** [comment]
Hey,

I'm Aanya Mishra, a passionate GSSoC participant eager to contribute to Squared-line. The "Ui Enhancement" issue caught my eye, and I believe my Frontend, Ui/Ux skills can be a great asset. I'm a quick learner and excited to contribute meaningfully. Would you be open to assigning this to me?

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Durgesh4993** [comment]
@Ramu-chiluveru @Aanya10Mishra @ridhi-ahuja Please raise any other issue, i'll assign you

**Comment by nidhaahmed** [comment]
> If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...
> 
> Thank you :)

Hey @Durgesh4993, thank you for assigning me.
