### ISSUE TITLE
Readme.md [Documentation Bug]: 

### ISSUE THREAD

**Issue by Meetjain1** [ChromeGaming/Squard-line#62]
### What's wrong with the existing documentation

currently in our readme.md file some sections are missing , 

@Durgesh4993  assign this issue to me I will add it .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### Provide step by step information reproduce the bug 📄

We can add to attract more contributors 
like Contributors section, Techstack in which we are currently working on section , working video of our project , connect with us section in which we can provide discord,linkedin links etc

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Meetjain1 Could you please explain more what you want to do,

**Comment by zerotwoadarsh** [comment]
I would like to work on this issue. Can you assign it to me?
