### ISSUE TITLE
[New Feature]: reDesign the welcome home page

### ISSUE THREAD

**Issue by Varsani2520** [ChromeGaming/Squard-line#75]
### 🎮 feature Request

feature logic and basic description
in welcome home page display animated video of 2 sec

### Point down the features

feature points
- add animated welcome video of 2 sec

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Varsani2520 Could you please explain more what you want to do, if possible you can also add screenshot.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)

**Comment by Varsani2520** [comment]
@Durgesh4993 ,

in your web:
![image](https://github.com/GameSphere-MultiPlayer/Squard-line/assets/137641079/80890f82-db60-4861-bb09-d10ca840199e)

like this on startup page:
![image](https://github.com/GameSphere-MultiPlayer/Squard-line/assets/137641079/e01eba97-de8a-44ca-a3b3-719c32506409)

**Comment by Varsani2520** [comment]
Hi @Durgesh4993 ,can you solved my question

**Comment by Durgesh4993** [comment]
?

**Comment by Varsani2520** [comment]
this is my personal question,
my PR is merged but my name is not display in contributor why ?
screenshot is:
![image](https://github.com/GameSphere-MultiPlayer/Squard-line/assets/137641079/3f11e5b2-b182-4e19-b1b0-e767fd6b9323)
can you solved my problem

actually this is related to another repo but i wish to help me

**Comment by Durgesh4993** [comment]
It is not a issue

**Comment by Durgesh4993** [comment]
You PR has been merged and proper levels are used they will counted in your score

**Comment by Durgesh4993** [comment]
No neer to worry about tha

**Comment by Varsani2520** [comment]
@Durgesh4993 ,thank you :)
