### ISSUE TITLE
[Bug]: The website is not responsive in mobile view

### ISSUE THREAD

**Issue by alok2424** [ChromeGaming/Squard-line#81]
### Give a brief about the bug ✍️

As we are opening the website in the laptop it is working fine, but as I open it in mobile , it is not responsive. Hence ,it's a major issue for mobile users.

https://github.com/GameSphere-MultiPlayer/Squard-line/assets/130597958/a671f3f8-878e-4a88-b0ea-580be41ce433

### What is the expected behavior? 🤔

In both laptop and mobile view , the game must be appear on the center of the screen so that user can play the game.

### Provide step by step information reproduce the bug 📄

Step-1: Go to the home page 
Step-2: Change the view to mobile view
Step-3: The game will not align at the center.
Step-4: Simply go to the style component in the index.html file.
Step-5: Add external CSS in order to justify the content at the center.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by heli0707** [comment]
I would like to work on this please assign it to me

**Comment by Garvanand** [comment]
Kindly assign to me ,I have rectified the issue
