### ISSUE TITLE
 Feature Request: Introduction of Squard-line Homepage

### ISSUE THREAD

**Issue by Ayushvishwakarma04** [ChromeGaming/Squard-line#82]
### feature logic and basic description:
We propose implementing a dedicated homepage for Squard-line, our flagship game. This homepage will serve as a central hub for players to access essential game information, interesting facts, a high scores leaderboard, and a section redirecting to the main game page for further exploration.

### feature points:
**Game Information Section:** The homepage will provide a brief overview of Squard-line, including its storyline, gameplay mechanics, and key features. This section aims to give players a quick understanding of what the game entails and why it's worth playing.

**Fun Facts Segment:** Players will discover intriguing facts about Squard-line, such as development insights, hidden secrets within the game, and notable achievements. These fun facts add an element of surprise and entertainment for players, encouraging them to explore the game further.

**High Scores Leaderboard:** A prominent feature of the homepage will be the leaderboard showcasing the highest scores achieved by players. This leaderboard fosters healthy competition among players, motivating them to improve their skills and strive for the top spots.

**Main Game Page Section:** An additional section will provide a direct link to the main game page, allowing players to seamlessly transition to the full game experience. This ensures that players have easy access to the game itself, where they can dive deeper into gameplay and engage with additional features.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Ayushvishwakarma04** [comment]
Hello! 😊 I'd appreciate being assigned this task under GSSoC 24.

**Comment by Tarungupta18** [comment]
assign me
