### ISSUE TITLE
[Enhancement]: Changing the alert into dialogue box

### ISSUE THREAD

**Issue by 18Venus** [ChromeGaming/Squard-line#83]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The game has alerts on entering and losing. It can rather have dialogue boxes with more options like 'New Game', 'End Game' etc thus adding better UI along with new features.

![gameui](https://github.com/GameSphere-MultiPlayer/Squard-line/assets/149051659/7c9bcf14-4811-4251-8f86-925c77f0f409)

### Describe the solution you'd like

We can have dialogue boxes at the center popping instead of alerts!

Pls assign this work to me under GSSoC'24! Thankyou!

### Select program in which you are contributing

GSSoC23, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by nihasinghania22** [comment]
could you please assign me this issue

**Comment by Tarungupta18** [comment]
please assign me

**Comment by dvnshi** [comment]
Please assign this issue to me under GSSOC .
