### ISSUE TITLE
[Documentation Bug]: Missing git pull command in Readme.md

### ISSUE THREAD

**Issue by Amruta7203** [ChromeGaming/Squard-line#90]
### Describe the bug ✍️

There is a missing git pull upstream main command in the readme.md file
This command is important to ensure that the changes are made in the updated code.

### Provide step by step information reproduce the bug 📄

Adding the <git pull upstream main>

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by zerotwoadarsh** [comment]
I would like to work on this issue. Can you assign it to me?
