### ISSUE TITLE
[New Feature]: Redirecting the social media links to a new tab

### ISSUE THREAD

**Issue by Amruta7203** [ChromeGaming/Squard-line#91]
### 🎮 feature Request

Currently the social media links are opening in the same tab as the game website. This decrease user experience.

### Point down the features

I propose redirecting the social media links to a new tab to improve user convenience and experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by yeolesanskruti** [comment]
@Amruta7203  @Durgesh4993  
I want to work on this issue. Will you please assign it to me under GSSoC'24?

**Comment by dvnshi** [comment]
Please assign this issue to me under GSSOC .
