### ISSUE TITLE
[New Feature]:Button to navigate to the main page  

### ISSUE THREAD

**Issue by triggereddown** [ChromeGaming/Squard-line#94]
### 🎮 feature Request

Would like to try and add a back button to return to the main page rather than closing the web app directly

### Point down the features

1. Will add a new feature to go back to the initial page if possible
2. Will try to implement and match the theme with the website 
3. If possible font will be needed for better UI blending

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@triggereddown Could you please explain more what you want to do, if possible you can also add screenshot.

**Comment by triggereddown** [comment]
![image](https://github.com/ChromeGaming/Squard-line/assets/137756305/9f79cb8e-2391-4839-8389-9451147fab93)
![image](https://github.com/ChromeGaming/Squard-line/assets/137756305/a851d08d-db4b-478d-84d0-88f69de93d22)
#From the second page to the front page there is no back button to go to the previous menu only to reload the page and get to it, i was thinking to finding a way to add a button which can redirect to the previous page again

**Comment by Mukesh751** [comment]
Someone is already working on similar issue #65, if your issue is different then please elaborate.

**Comment by triggereddown** [comment]
I beleive it's the same going back and exiting the game page . Sorry i overlooked

**Comment by Mukesh751** [comment]
Thanks for confirmation. I'm closing this issue now. Please raise a new PR for contribution.

Have a Great Day!!!
