### ISSUE TITLE
Login / SignUp

### ISSUE THREAD

**Issue by himadeepthi1** [ChromeGaming/Squard-line#95]
### 🎮 feature Request

feature logic and basic description
Would like to a Login/Sign Up option

### Point down the features

I will add a login/Sign Up option
if users could log in and play the game, then their  high score, achievements regarding the game  would be added to their profile

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by dvnshi** [comment]
Please assign this issue to me under GSSOC .
